# Generated by Django 4.1.2 on 2022-10-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPENED", "Opened"),
                            ("ACTIVE", "Active"),
                            ("FINISHED", "Finished"),
                        ],
                        max_length=8,
                    ),
                ),
            ],
        ),
    ]
