# Generated by Django 4.1.2 on 2022-11-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_team_players"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="teams",
        ),
        migrations.AddField(
            model_name="tournament",
            name="participants",
            field=models.ManyToManyField(
                db_table="tournaments_participants",
                related_name="tournaments",
                to="app.team",
            ),
        ),
    ]
