# Generated by Django 4.1.2 on 2022-11-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="stage",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
